version: '3.8'

services:
  generator:
    container_name: generator 
    build:
      context: .
    ports:
      - "8888:8888"  # Expose Jupyter Notebook
    volumes:
      - ./notebooks:/home/myenv/notebooks
      - ./requirements.txt:/home/myenv/requirements.txt
    command: >
      sh -c "pip install -r /home/myenv/requirements.txt &&
             jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root"
