title="OntoRaster Demonstration"

[[tabGroups]]

name="Examples"

[[tabGroups.tabs]]

name="Calculate Spatial Average Over User Specific Vector Region (polygon_wkt) and Raster"
query="""
PREFIX :	<http://www.semanticweb.org/arkaghosh/OntoRaster/>
PREFIX rdfs:	<http://www.w3.org/2000/01/rdf-schema#>
PREFIX geo:	<http://www.opengis.net/ont/geosparql#>
PREFIX rasdb:	<http://www.semanticweb.org/RasterDataCube/>

SELECT ?v {
?vector rdfs:label ?vector_region_name .
?vector geo:asWKT ?vector_region_wkt .
?raster rasdb:hasRasterName ?raster_name .
FILTER (?vector_region_name = 'München')
FILTER (CONTAINS(?raster_name, 'Bavaria'))
BIND ('2023-07-24T00:00:00+00:00' AS ?timestamp)
BIND (rasdb:rasSpatialAverageFINAL(?timestamp, ?vector_region_wkt, ?raster_name) AS ?v)
}
"""

[[tabGroups.tabs]]

name="Calculate Spatial Average Over User Specific Vector Region (multipolygon_wkt) and Raster"
query="""
PREFIX :	<http://www.semanticweb.org/arkaghosh/OntoRaster/>
PREFIX rdfs:	<http://www.w3.org/2000/01/rdf-schema#>
PREFIX geo:	<http://www.opengis.net/ont/geosparql#>
PREFIX rasdb:	<http://www.semanticweb.org/RasterDataCube/>

SELECT ?v {
?vector rdfs:label ?vector_region_name .
?vector geo:asWKT ?vector_region_wkt .
?raster rasdb:hasRasterName ?raster_name .
FILTER (?vector_region_name = 'Göteborg')
FILTER (CONTAINS(?raster_name, 'Sweden'))
BIND ('2022-08-24T00:00:00+00:00' AS ?timestamp)
BIND (rasdb:rasSpatialAverageFINAL(?timestamp, ?vector_region_wkt, ?raster_name) AS ?v)
}
"""

[[tabGroups.tabs]]

name="Q9. Clip Raster based on Region "
query="""
PREFIX :	<http://www.semanticweb.org/arkaghosh/OntoRaster/>
PREFIX rdfs:	<http://www.w3.org/2000/01/rdf-schema#>
PREFIX geo:	<http://www.opengis.net/ont/geosparql#>
PREFIX rasdb:	<http://www.semanticweb.org/RasterDataCube/>

SELECT ?answer {
?vector rdfs:label ?vector_region_name .
?vector geo:asWKT ?vector_region_wkt .
?raster rasdb:hasRasterName ?raster_name .
FILTER (?vector_region_name = 'Castelrotto')
FILTER (CONTAINS(?raster_name, 'Tyrol'))
BIND ('2023-09-24T00:00:00+00:00' AS ?timestamp)
BIND (rasdb:rasClipRaster(?timestamp, ?vector_region_wkt, ?raster_name) AS ?answer)
}
"""

[[tabGroups.tabs]]

name="Clip Raster over any custom geometry over user specific raster"
query="""
PREFIX :	<http://www.semanticweb.org/arkaghosh/OntoRaster/>
PREFIX rdfs:	<http://www.w3.org/2000/01/rdf-schema#>
PREFIX geo:	<http://www.opengis.net/ont/geosparql#>
PREFIX rasdb:	<http://www.semanticweb.org/RasterDataCube/>

SELECT ?v {
?raster rasdb:hasRasterName ?raster_name .
BIND ('POLYGON((11.324157714843748 48.29050321714061,11.911926269531248 48.279537342260085,11.88995361328125 48.01932418480118,11.340637207031248 48.01564978668938,11.324157714843748 48.29050321714061))' AS ?custom_region_wkt)
FILTER (CONTAINS(?raster_name, 'Bavaria'))
BIND ('2023-07-24T00:00:00+00:00' AS ?timestamp)
BIND (rasdb:rasClipRasterAnyGeom(?timestamp, ?custom_region_wkt, ?raster_name) AS ?v)
}
"""
