title="OntoRaster Demonstration"

[[tabGroups]]

name="RasSPARQL Queries"

[[tabGroups.tabs]]

name="Q1. Get Dimension"
query="""
#####################################################################
#### Query 1. Find the dimension of user-specific Raster dataset ####
#####################################################################

PREFIX :	<http://www.semanticweb.org/arkaghosh/OntoRaster/>
PREFIX rasdb:	<http://www.semanticweb.org/RasterDataCube/>

SELECT ?answer {
?gridCoverage a :Raster .
?gridCoverage rasdb:rasterName ?rasterName .
FILTER (CONTAINS(?rasterName, 'Bavaria'))
BIND (rasdb:rasDimension(?rasterName) AS ?answer)
}
"""

[[tabGroups.tabs]]

name="Q2. Cell Operation"
query="""
#################################################################################################################
#### Query 2. Perform element-wise operation over raster array cells with user-specific operator and operand ####
#################################################################################################################

PREFIX :	<http://www.semanticweb.org/arkaghosh/OntoRaster/>
PREFIX rasdb:	<http://www.semanticweb.org/RasterDataCube/>

SELECT ?answer {
?raster rasdb:rasterName ?raster_name .
FILTER (CONTAINS(?rasterName, 'Sweden'))
BIND ('*' AS ?operator) 
BIND (0.02 AS ?operand)
BIND ('2022-04-18T00:00:00+00:00'^^xsd:dateTime AS ?timeStamp)
BIND (rasdb:rasCellOp(?timeStamp, ?operator, ?operand, ?rasterName) AS ?answer)
}
"""

[[tabGroups.tabs]]

name="Q3. Spatial Average"
query="""
###################################################################################################
#### Query 3. Find spatial average value over a user-specific vector Region and Raster dataset ####
###################################################################################################

PREFIX :	<http://www.semanticweb.org/arkaghosh/OntoRaster/>
PREFIX rdfs:	<http://www.w3.org/2000/01/rdf-schema#>
PREFIX geo:	<http://www.opengis.net/ont/geosparql#>
PREFIX rasdb:	<http://www.semanticweb.org/RasterDataCube/>

SELECT ?answer {
?region a :Region .
?region rdfs:label ?regionName .
?region geo:asWKT ?regionWkt .
?gridCoverage a :Raster .
?gridCoverage rasdb:rasterName ?rasterName .
FILTER (?regionName = 'München') # also try with Daggendorf, Bayreuth, Würzburg etc.         
FILTER (CONTAINS(?rasterName, 'Bavaria'))
BIND ('2023-09-04T00:00:00+00:00'^^xsd:dateTime AS ?timeStamp)
BIND (rasdb:rasSpatialAverage(?timeStamp, ?regionWkt, ?rasterName) AS ?answer)
} 
"""

[[tabGroups.tabs]]

name="Q4. Spatial Maximum"
query="""
###################################################################################################
#### Query 4. Find spatial maximum value over a user-specific vector Region and Raster dataset ####
###################################################################################################

PREFIX :	<http://www.semanticweb.org/arkaghosh/OntoRaster/>
PREFIX rdfs:	<http://www.w3.org/2000/01/rdf-schema#>
PREFIX geo:	<http://www.opengis.net/ont/geosparql#>
PREFIX rasdb:	<http://www.semanticweb.org/RasterDataCube/>

SELECT ?answer {
?region a :Region .
?region rdfs:label ?regionName .
?region geo:asWKT ?regionWkt .
?gridCoverage a :Raster .
?gridCoverage rasdb:rasterName ?rasterName .
FILTER (?regionName = 'Söderköping') # also try with Linköping, Uppsala, Göteborg, Stockholm etc.
FILTER (CONTAINS(?rasterName, 'Sweden'))
BIND ('2022-08-24T00:00:00+00:00'^^xsd:dateTime AS ?timeStamp)
BIND (rasdb:rasSpatialMaximum(?timeStamp, ?regionWkt, ?rasterName) AS ?answer)
} 
"""

[[tabGroups.tabs]]

name="Q5. Spatial Minimum"
query="""
###################################################################################################
#### Query 5. Find spatial minimum value over a user-specific vector Region and Raster dataset ####
###################################################################################################

PREFIX :	<http://www.semanticweb.org/arkaghosh/OntoRaster/>
PREFIX rdfs:	<http://www.w3.org/2000/01/rdf-schema#>
PREFIX geo:	<http://www.opengis.net/ont/geosparql#>
PREFIX rasdb:	<http://www.semanticweb.org/RasterDataCube/>

SELECT ?answer {
?region a :Region .
?region rdfs:label ?regionName .
?region geo:asWKT ?regionWkt .
?gridCoverage a :Raster .
?gridCoverage rasdb:rasterName ?rasterName .
FILTER (?regionName = 'Bolzano') # also try with Castelrotto, Sarentino, Fortezza  etc.
FILTER (CONTAINS(?rasterName, 'Tyrol'))
BIND ('2023-03-03T00:00:00+00:00'^^xsd:dateTime AS ?timeStamp)
BIND (rasdb:rasSpatialMinimum(?timeStamp, ?regionWkt, ?rasterName) AS ?answer)
} 
"""

[[tabGroups.tabs]]

name="Q6. Temporal Average"
query="""
###########################################################################################################################
#### Query 6. Find temporal average value over a user-specific vector Region and Raster dataset between two timestamps ####
###########################################################################################################################

PREFIX :	<http://www.semanticweb.org/arkaghosh/OntoRaster/>
PREFIX rdfs:	<http://www.w3.org/2000/01/rdf-schema#>
PREFIX geo:	<http://www.opengis.net/ont/geosparql#>
PREFIX rasdb:	<http://www.semanticweb.org/RasterDataCube/>

SELECT ?answer {
?region a :Region .
?region rdfs:label ?regionName .
?region geo:asWKT ?regionWkt .
?gridCoverage a :Raster .
?gridCoverage rasdb:rasterName ?rasterName .
FILTER (CONTAINS(?regionName, 'Cham')) 
FILTER (?regionName = 'Bavaria')
BIND ('2023-06-15T00:00:00+00:00'^^xsd:dateTime AS ?startTimeStamp)
BIND ('2023-07-21T00:00:00+00:00'^^xsd:dateTime AS ?endTimeStamp)
BIND (rasdb:rasTemporalAverage(?startTimeStamp, ?endTimeStamp , ?regionWkt, ?rasterName) AS ?answer)
} 
"""

[[tabGroups.tabs]]

name="Q7. Temporal Maximum"
query="""
###########################################################################################################################
#### Query 7. Find temporal maximum value over a user-specific vector Region and Raster dataset between two timestamps ####
###########################################################################################################################

PREFIX :	<http://www.semanticweb.org/arkaghosh/OntoRaster/>
PREFIX rdfs:	<http://www.w3.org/2000/01/rdf-schema#>
PREFIX geo:	<http://www.opengis.net/ont/geosparql#>
PREFIX rasdb:	<http://www.semanticweb.org/RasterDataCube/>

SELECT ?answer {
?region a :Region .
?region rdfs:label ?regionName .
?region geo:asWKT ?regionWkt .
?gridCoverage a :Raster .
?gridCoverage rasdb:rasterName ?rasterName .
FILTER (?regionName = 'Göteborg') 
FILTER (CONTAINS(?rasterName, 'Sweden'))
BIND ('2022-04-05T00:00:00+00:00'^^xsd:dateTime AS ?startTimeStamp)
BIND ('2022-06-19T00:00:00+00:00'^^xsd:dateTime AS ?endTimeStamp)
BIND (rasdb:rasTemporalMaximum(?startTimeStamp, ?endTimeStamp , ?regionWkt, ?rasterName) AS ?answer)
} 
"""

[[tabGroups.tabs]]

name="Q8. Temporal Minimum"
query="""
###########################################################################################################################
#### Query 8. Find temporal minimum value over a user-specific vector Region and Raster dataset between two timestamps ####
###########################################################################################################################

PREFIX :	<http://www.semanticweb.org/arkaghosh/OntoRaster/>
PREFIX rdfs:	<http://www.w3.org/2000/01/rdf-schema#>
PREFIX geo:	<http://www.opengis.net/ont/geosparql#>
PREFIX rasdb:	<http://www.semanticweb.org/RasterDataCube/>

SELECT ?answer {
?region a :Region .
?region rdfs:label ?regionName .
?region geo:asWKT ?regionWkt .
?gridCoverage a :Raster .
?gridCoverage rasdb:rasterName ?rasterName .
FILTER (?regionName = 'Sarentino') 
FILTER (CONTAINS(?rasterName, 'Tyrol'))
BIND ('2023-07-15T00:00:00+00:00'^^xsd:dateTime AS ?startTimeStamp)
BIND ('2023-07-21T00:00:00+00:00'^^xsd:dateTime AS ?endTimeStamp)
BIND (rasdb:rasTemporalMinimum(?startTimeStamp, ?endTimeStamp , ?regionWkt, ?rasterName) AS ?answer)
} 
"""

[[tabGroups.tabs]]

name="Q9. Clip Raster"
query="""
#####################################################################################################################
#### Query 9. Clip a portion of the raster based on the shape of vector Region over user-specific raster dataset ####
#####################################################################################################################

PREFIX :	<http://www.semanticweb.org/arkaghosh/OntoRaster/>
PREFIX rdfs:	<http://www.w3.org/2000/01/rdf-schema#>
PREFIX geo:	<http://www.opengis.net/ont/geosparql#>
PREFIX rasdb:	<http://www.semanticweb.org/RasterDataCube/>

SELECT ?answer {
?region a :Region .
?region rdfs:label ?regionName .
?region geo:asWKT ?regionWkt .
?gridCoverage a :Raster .
?gridCoverage rasdb:rasterName ?rasterName .
FILTER (?regionName = 'Castelrotto') 
FILTER (CONTAINS(?rasterName, 'Tyrol')) 
BIND ('2023-09-24T00:00:00+00:00'^^xsd:dateTime AS ?timeStamp)
BIND (rasdb:rasClipRaster(?timeStamp, ?regionWkt, ?rasterName) AS ?answer) 
}
"""

[[tabGroups.tabs]]

name="Q10. Clip Raster Custom Region"
query="""
#################################################################################################################################
#### Query 10. Clip a portion of the raster based on the shape of the custom vector Region over user-specific raster dataset ####
#################################################################################################################################

PREFIX :	<http://www.semanticweb.org/arkaghosh/OntoRaster/>
PREFIX rdfs:	<http://www.w3.org/2000/01/rdf-schema#>
PREFIX geo:	<http://www.opengis.net/ont/geosparql#>
PREFIX rasdb:	<http://www.semanticweb.org/RasterDataCube/>

SELECT ?answer {
?gridCoverage a :Raster .
?gridCoverage rasdb:rasterName ?rasterName .
FILTER (CONTAINS(?rasterName, 'Bavaria')) 
BIND ('POLYGON((11.324157714843748 48.29050321714061,11.911926269531248 48.279537342260085,11.88995361328125 48.01932418480118,11.340637207031248 48.01564978668938,11.324157714843748 48.29050321714061))' AS ?customRegionWkt)
BIND ('2023-07-24T00:00:00+00:00'^^xsd:dateTime AS ?timeStamp)
BIND (rasdb:rasClipRasterAnyGeom(?timeStamp, ?customRegionWkt, ?rasterName) AS ?answer) 
}
"""