title="OntoRaster Demonstration"

[[tabGroups]]

name="RasSPARQL Queries"

[[tabGroups.tabs]]

name="Query 1. Get Dimension"
query="""
#####################################################################
#### Query 1. Find the dimension of user-specific Raster dataset ####
#####################################################################

PREFIX :	<http://www.semanticweb.org/arkaghosh/OntoRaster/>
PREFIX rasdb:	<http://www.semanticweb.org/RasterDataCube/>

SELECT ?answer {
?raster rasdb:hasRasterName ?raster_name .
FILTER (CONTAINS(?raster_name, 'Bavaria'))
BIND (rasdb:rasDimension(?raster_name) AS ?answer)
}
"""

[[tabGroups.tabs]]

name="Query 2"
query="""
#####################################################################
#### Query 2.
#####################################################################
"""

[[tabGroups.tabs]]

name="Query 3"
query="""
#####################################################################
#### Query 3.
#####################################################################
"""

[[tabGroups.tabs]]

name="Query 4"
query="""
#####################################################################
#### Query 4.
#####################################################################
"""

[[tabGroups.tabs]]

name="Query 5"
query="""
#####################################################################
#### Query 5.
#####################################################################
"""

[[tabGroups.tabs]]

name="Query 6. Spatial Average"
query="""
#############################################################################################################
#### Query 6. Find spatial average value over a user-specific vector Region (Polygon) and Raster dataset ####
#############################################################################################################

PREFIX :	<http://www.semanticweb.org/arkaghosh/OntoRaster/>
PREFIX rdfs:	<http://www.w3.org/2000/01/rdf-schema#>
PREFIX geo:	<http://www.opengis.net/ont/geosparql#>
PREFIX rasdb:	<http://www.semanticweb.org/RasterDataCube/>

SELECT ?answer {
?vector rdfs:label ?vector_region_name .
?vector geo:asWKT ?vector_region_wkt .
?raster rasdb:hasRasterName ?raster_name .
FILTER (?vector_region_name = 'München')
FILTER (CONTAINS(?raster_name, 'Bavaria'))
BIND ('2023-07-24T00:00:00+00:00' AS ?timestamp)
BIND (rasdb:rasSpatialAverageFINAL(?timestamp, ?vector_region_wkt, ?raster_name) AS ?answer)
}
"""

[[tabGroups.tabs]]

name="Query 7. Spatial Maximum"
query="""
#############################################################################################################
#### Query 7. Find spatial maximum value over a user-specific vector Region (MultiPolygon) and Raster dataset ####
#############################################################################################################

PREFIX :	<http://www.semanticweb.org/arkaghosh/OntoRaster/>
PREFIX rdfs:	<http://www.w3.org/2000/01/rdf-schema#>
PREFIX geo:	<http://www.opengis.net/ont/geosparql#>
PREFIX rasdb:	<http://www.semanticweb.org/RasterDataCube/>

SELECT ?answer {
?vector rdfs:label ?vector_region_name .
?vector geo:asWKT ?vector_region_wkt .
?raster rasdb:hasRasterName ?raster_name .
FILTER (?vector_region_name = 'Göteborg')
FILTER (CONTAINS(?raster_name, 'Sweden'))
BIND ('2022-08-24T00:00:00+00:00' AS ?timestamp)
BIND (rasdb:rasSpatialAverageFINAL(?timestamp, ?vector_region_wkt, ?raster_name) AS ?answer)
}
"""

[[tabGroups.tabs]]

name="Query 8. Spatial Minimum"
query="""
#############################################################################################################
#### Query 8. Find spatial minimum value over a user-specific vector Region (Polygon) and Raster dataset ####
#############################################################################################################

PREFIX :	<http://www.semanticweb.org/arkaghosh/OntoRaster/>
PREFIX rdfs:	<http://www.w3.org/2000/01/rdf-schema#>
PREFIX geo:	<http://www.opengis.net/ont/geosparql#>
PREFIX rasdb:	<http://www.semanticweb.org/RasterDataCube/>

SELECT ?answer {
?vector rdfs:label ?vector_region_name .
?vector geo:asWKT ?vector_region_wkt .
?raster rasdb:hasRasterName ?raster_name .
FILTER (?vector_region_name = 'Ultimo')
FILTER (CONTAINS(?raster_name, 'Tyrol'))
BIND ('2023-07-24T00:00:00+00:00' AS ?timestamp)
BIND (rasdb:rasSpatialAverageFINAL(?timestamp, ?vector_region_wkt, ?raster_name) AS ?answer)
}
"""


[[tabGroups.tabs]]

name="Query 9. Clip Raster"
query="""
#####################################################################################################################
#### Query 9. Clip a portion of the raster based on the shape of vector Region over user-specific raster dataset ####
#####################################################################################################################

PREFIX :	<http://www.semanticweb.org/arkaghosh/OntoRaster/>
PREFIX rdfs:	<http://www.w3.org/2000/01/rdf-schema#>
PREFIX geo:	<http://www.opengis.net/ont/geosparql#>
PREFIX rasdb:	<http://www.semanticweb.org/RasterDataCube/>

SELECT ?answer {
?vector rdfs:label ?vector_region_name .
?vector geo:asWKT ?vector_region_wkt .
?raster rasdb:hasRasterName ?raster_name .
FILTER (?vector_region_name = 'Castelrotto')
FILTER (CONTAINS(?raster_name, 'Tyrol'))
BIND ('2023-09-24T00:00:00+00:00' AS ?timestamp)
BIND (rasdb:rasClipRaster(?timestamp, ?vector_region_wkt, ?raster_name) AS ?answer)
}
"""

[[tabGroups.tabs]]

name="Query 10. Clip Raster Custom Region"
query="""

#################################################################################################################################
#### Query 10. Clip a portion of the raster based on the shape of the custom vector Region over user-specific raster dataset ####
#################################################################################################################################

PREFIX :	<http://www.semanticweb.org/arkaghosh/OntoRaster/>
PREFIX rdfs:	<http://www.w3.org/2000/01/rdf-schema#>
PREFIX geo:	<http://www.opengis.net/ont/geosparql#>
PREFIX rasdb:	<http://www.semanticweb.org/RasterDataCube/>

SELECT ?answer {
?raster rasdb:hasRasterName ?raster_name .
BIND ('POLYGON((11.324157714843748 48.29050321714061,11.911926269531248 48.279537342260085,11.88995361328125 48.01932418480118,11.340637207031248 48.01564978668938,11.324157714843748 48.29050321714061))' AS ?custom_region_wkt)
FILTER (CONTAINS(?raster_name, 'Bavaria'))
BIND ('2023-07-24T00:00:00+00:00' AS ?timestamp)
BIND (rasdb:rasClipRasterAnyGeom(?timestamp, ?custom_region_wkt, ?raster_name) AS ?answer)
}
"""
