version: "3.4"

services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "${MAPPED_POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres2024
  ontop:
    image: ontop/ontop:5.0.2
    env_file: .env
    restart: unless-stopped
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/dest-solution.ttl
      ONTOP_XML_CATALOG_FILE: /opt/ontop/input/catalog-v001.xml
      ONTOP_MAPPING_FILE: /opt/ontop/input/OntoRaster.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/OntoRaster.properties
      ONTOP_PORTAL_FILE: /opt/ontop/input/dest.portal.toml
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
      ONTOP_DEV_MODE: "true"
    volumes:
      - ./vkg:/opt/ontop/input
      - ./jdbc:/opt/ontop/jdbc
      - ./wait-for-it:/opt/wait-for-it
    entrypoint:
        [
          "/opt/wait-for-it/wait-for-it.sh",
          "db:5432",
          "--timeout=0",
          "--strict",
          "--",
          "/opt/ontop/entrypoint.sh",
        ]
    ports:
      - "${SERVER_PORT}:8080"
